language: cpp
branches:
  only:
  - master
  - dev
  - "/^\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
  - ipfs
env:
  global:
  - secure: NQkUI+wzCWsWJ3uQO10RVl2uhfKucm6154DWivmA1cF7ozillacb8Bt6B67oGx1uHeDR8kDazW9yUFei6Q2Oz+UWOKJEg0u+yYSCoelh2QrWiKQA0JCDUYhF37ySQH5Wu2xlGF+TRLMN8+tQNGeDceA0J1grH08cXSToH3G2MF2BIDQDKz4EQon4FN1J3CD8Nqu79Q+KXSSBAQ9QtpFd06cabZA62AkoD7nxvMXByS8gKU6KuJhZ1uH73leZtWCNmGapktRds6Yslndqk4wngSkjZLszlG8FQaIVQLputdWbC8uqfB2rgjbi0ye2fhr9BUOEBgPxbPoUylY4stZxeusnPT9tpRDa7L0EleDkTa7GEhmG55+8QYuZdAaY8+opmAG6i0VWTfSR8ZDkfC1usnYUxoRSSUnLqhJ2BsFo70A9GX4t1W3UYlPlGME2WQmPM9r1UdjtJLg65ig45TnJFnnouyOXzjwsN93hBhisLcVoFpJH60MbJH1krk6wBpeVvncWKhTwcmRx/OrgmGrNP+OYwlQSXkdIICgB7CybQ6LGlU6jXdYo20OnJkVCrxmJoHbJOFZZbZfmDEO0c1JuGoXW9uNC+7Xh3nCpzEaVl6f7nwJ9LXXGFOcoDSDskTHc118A5jHEIKbWmiTS3iSTMkl91uOjz0xlDMm4tXjTu4o=
matrix:
  include:
  - os: linux
    if: branch = master || branch = dev || ipfs
    dist: trusty
    sudo: required
    before_install:
    - openssl aes-256-cbc -k "$decrypt_keys" -in /home/travis/build/subutai-io/control-center/travis.tar.gz.enc -out /home/travis/build/subutai-io/control-center/travis.tar.gz -d
    - tar -xf travis.tar.gz -C /home/travis/build/subutai-io/control-center/
    - gpg --allow-secret-key-import --import /home/travis/build/subutai-io/control-center/jenkins-subutai && rm -f /home/travis/build/subutai-io/control-center/jenkins-subutai
    - gpg --allow-secret-key-import --import /home/travis/build/subutai-io/control-center/jenkins-optdyn && rm -f /home/travis/build/subutai-io/control-center/jenkins-optdyn
    - LD_LIBRARY_PATH=/usr/local/lib64/:$LD_LIBRARY_PATH
    - export LD_LIBRARY_PATH
    - sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get install gcc-4.9 g++-4.9 libicu52 devscripts libssh2-1-dev libxi-dev
      libxcb-xkb-dev libxrender-dev libxcb-image0-dev libxcb-render-util0-dev libxcb-icccm4-dev
      libxcb-keysyms1-dev libxcb-xinerama0-dev libdconf-dbus-1-dev dh-autoreconf
    script:
    - sudo mkdir -p /home/builder/ && sudo chmod 777 /home/builder/
    - wget -nv -O /home/builder/qt_static.tar.gz https://cdn.subutai.io:8338/kurjun/rest/raw/download?name=qt_static.tar.gz
      && tar -xf /home/builder/qt_static.tar.gz -C /home/builder/
    - wget -nv -O /home/travis/build/subutai-io/control-center/libs.tar.gz https://cdn.subutai.io:8338/kurjun/rest/raw/download?name=libs.tar.gz
      && tar -xf libs.tar.gz
    - sudo /home/travis/build/subutai-io/control-center/./build_linux.sh $TRAVIS_BRANCH
    - ls subutai_control_center_bin
    deploy:
    - provider: script
      script: sudo bash upload-ipfs.sh $TRAVIS_BRANCH
      skip_cleanup: true
      on:
        branch: ipfs
    - provider: script
      script: sudo bash upload.sh $TRAVIS_BRANCH
      skip_cleanup: true
      on:
        branch: dev
    - provider: script
      script: bash upload.sh $TRAVIS_BRANCH
      skip_cleanup: true
      on:
        branch: master
    - provider: script
      script: bash upload.sh HEAD
      skip_cleanup: true
      on:
        tags: true
  - os: osx
    osx_image: xcode9
    before_install:
    - openssl aes-256-cbc -k "$decrypt_keys" -in /Users/travis/build/subutai-io/control-center/travis.tar.gz.enc -out /Users/travis/build/subutai-io/control-center/travis.tar.gz -d
    - tar -xf travis.tar.gz -C /Users/travis/build/subutai-io/control-center/
    - gpg --allow-secret-key-import --import /Users/travis/build/subutai-io/control-center/jenkins-subutai && rm -f /Users/travis/build/subutai-io/control-center/jenkins-subutai
    - gpg --allow-secret-key-import --import /Users/travis/build/subutai-io/control-center/jenkins-optdyn && rm -f /Users/travis/build/subutai-io/control-center/jenkins-optdyn
    script:
    - sudo mkdir /Users/dev/ && sudo chmod 777 /Users/dev/
    - wget -nv -O /Users/dev/Qt5.9.2.tar.gz https://cdn.subutai.io:8338/kurjun/rest/raw/download?name=Qt5.9.2.tar.gz && tar -xf /Users/dev/Qt5.9.2.tar.gz -C /Users/dev
    - wget -nv -O /Users/travis/build/subutai-io/control-center/libs.tar.gz https://cdn.subutai.io:8338/kurjun/rest/raw/download?name=libs.tar.gz && tar -xf libs.tar.gz
    - sudo /Users/travis/build/subutai-io/control-center/./build_mac.sh $TRAVIS_BRANCH
    - "/Users/travis/build/subutai-io/control-center/upload_app.sh $TRAVIS_BRANCH"
    - ls subutai_control_center_bin
    deploy:
    - provider: script
      script: sudo bash upload-ipfs.sh $TRAVIS_BRANCH
      skip_cleanup: true
      on:
        branch: ipfs
    - provider: script
      script: sudo bash upload.sh $TRAVIS_BRANCH
      skip_cleanup: true
      on:
        branch: dev
    - provider: script
      script: bash upload.sh $TRAVIS_BRANCH
      skip_cleanup: true
      on:
        branch: master
    - provider: script
      script: bash upload.sh HEAD
      skip_cleanup: true
      on:
        tags: true
notifications:
  slack:
    secure: EiyEIfV7Ki+KyjiVS3UJqjtEjDWyERm9c7eW2DY5FzbZ2A4ZRZ1s3ZdTvQlEsVOgk4FCgezNgPfkPYEZubmgcDOP/HEpJf0cCnVc1UMfis9xI3BD0Xtek5uzriZGL+GuvHb0eXywD8MVQ3iwwVgCLQkEq11jWAJ/nZL4tzFxHLtJ4Xf6JTw5QPA2HlN7PfNVa87l6tPymLYJUPyZgVUTjj825R7KOh2oZrewPksuxJl9eV8V9rdpRGPg+t7jZno4KirkDp6HgAbrukiNdx5qp6EMDW6cgXy3cDcVXUmogzHT3MxSFFKmAlW8A5c2jtTnEB6FcNJ1IMeP54+CvvIS1ogR3TeSe30xlNluJAmvUQqGpmaDIWZTgChpJVo55NyU24g3Ia/cUG1P0MfbgIC5TfNtmKWcVKABDX9W4bNK8E1Lod7JiW6U0zFIhy1PUeRF4ifooL/LgnJdSZyyAhNPbTpV1DRbVjNiquRHF08bWJ9M1Xy5Qlt9EKOpYdOB8ukNW9Z/2DD19wZztGcynv0TfsO3e2IfvfcWzym/LeGushGw+qLvvo0VYfq1OqSAS9iYNVbAvPGA0f9MeiZbSbWsvLLyT4yLs1/nskW+iZ6KwQYBweqK+IQ//7Po4VNmzCRYdpfyN3s4aqwTyd7Kw+nps4wOEgHPjveL6yVtToSyjZI=
